codeBlue/urls.py
from django.conf.urls import url
from django.contrib import admin

from presentacion import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name="index"),

    # Calendar
    url(r'^calendar/$', views.calendar, name="calendar"),
    url(r'^calendar/event_added/$', views.calendar_eventadded, name="calendar_eventadded"),
    url(r'^calendar/add_event/(?P<event_id>[0-9]+)/$', views.calendar_add_event, name="add_event"),
    url(r'^calendar/oauth2callback$', views.calendar_auth_return, name="calendar_auth_return"),

    # Drive
    url(r'^drive/$', views.drive, name="drive"),
    #url(r'^calendar/event_added/$', views.calendar_eventadded, name="calendar_eventadded"),
    #url(r'^calendar/add_event/(?P<event_id>[0-9]+)/$', views.calendar_add_event, name="add_event"),
    url(r'^drive/oauth2callback$', views.drive_auth_return, name="drive_auth_return"),

    # URL shortener
    url(r'^shortener/$', views.shortener, name="shortener"),

    # Google Maps
    url(r'^maps/$', views.maps, name="gmaps"),

    # Translate
    url(r'^translate/$', views.translate, name="translator"),
]

presentacion/models.py
from django.db import models
from django.contrib.auth.models import User

from oauth2client.contrib.django_util.models import CredentialsField

# Create your models here.

class CredentialsModel(models.Model):
    user = models.OneToOneField(User)
    credential = CredentialsField()

class DriveCredentialsModel(models.Model):
    user = models.OneToOneField(User)
    credential = CredentialsField()

class Event(models.Model):
    summary = models.CharField(max_length=100)
    date = models.DateField()

presentacion/forms.py
from django import forms

class UrlForm(forms.Form):
    url = forms.CharField(max_length=200)

class TransForm(forms.Form):
    text = forms.CharField(max_length=200, widget = forms.Textarea)

presentacion/views.py
import httplib2

from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse_lazy
from django.conf import settings

from apiclient.discovery import build
from oauth2client.file import Storage
from oauth2client.client import OAuth2WebServerFlow
from oauth2client.client import flow_from_clientsecrets
from oauth2client.contrib import xsrfutil
from oauth2client.contrib.django_util.storage import DjangoORMStorage

from .models import CredentialsModel, DriveCredentialsModel, Event
from .forms import UrlForm, TransForm

# Create your views here.

CALENDAR_FLOW = OAuth2WebServerFlow(
    settings.GOOGLE_OAUTH2_CLIENT_ID,
    settings.GOOGLE_OAUTH2_CLIENT_SECRET,
    scope='https://www.googleapis.com/auth/calendar',
    redirect_uri='http://localhost:8000/calendar/oauth2callback'
)

DRIVE_FLOW = OAuth2WebServerFlow(
    settings.GOOGLE_OAUTH2_CLIENT_ID,
    settings.GOOGLE_OAUTH2_CLIENT_SECRET,
    scope='https://www.googleapis.com/auth/drive.metadata.readonly',
    redirect_uri='http://localhost:8000/drive/oauth2callback'
)

def index(request):
    return render(request, 'expo.html')

def calendar(request):
    context = {
        'events': Event.objects.all(),
    }
    if CredentialsModel.objects.filter(user=request.user).count() > 0:
        context['have_cred'] = True
    else:
        context['have_cred'] = False
    return render(request, 'calendar.html', context)

def calendar_eventadded(request):
    context = {
        'events': Event.objects.all(),
        'event_added': True,
    }

    if CredentialsModel.objects.filter(user=request.user).count() > 0:
        context['have_cred'] = True
    else:
        context['have_cred'] = False
    return render(request, 'calendar.html', context)

def calendar_add_event(request, event_id):
    storage = DjangoORMStorage(
        CredentialsModel,
        'user',
        request.user,
        'credential'
    )
    credential = storage.get()
    if credential is None or credential.invalid == True:
        CALENDAR_FLOW.params['state'] = xsrfutil.generate_token(settings.SECRET_KEY,
                                                       request.user)
        authorize_url = CALENDAR_FLOW.step1_get_authorize_url()
        return redirect(authorize_url)
    else:
        http = httplib2.Http()
        http = credential.authorize(http)

        event = Event.objects.get(pk=event_id)
        calendar_service = build('calendar', 'v3', http=http)
        body = {
            'start': { "date": str(event.date) },
            'end': { "date": str(event.date) },
            'summary': event.summary
        }
        calendar_request = calendar_service.events().insert(
            calendarId='primary',
            body=body,
        )
        response = calendar_request.execute()
        return redirect('calendar_eventadded')

def calendar_auth_return(request):
    if not xsrfutil.validate_token(
            settings.SECRET_KEY,
            bytes(request.GET['state'], 'utf-8'),
            request.user):
        return  HttpResponseBadRequest()
    credential = CALENDAR_FLOW.step2_exchange(request.GET)
    storage = DjangoORMStorage(CredentialsModel, 'user', request.user, 'credential')
    storage.put(credential)
    return redirect('calendar')

def drive(request):
    context = {}

    storage = DjangoORMStorage(
        DriveCredentialsModel,
        'user',
        request.user,
        'credential'
    )
    credential = storage.get()
    if credential is None or credential.invalid == True:
        DRIVE_FLOW.params['state'] = xsrfutil.generate_token(settings.SECRET_KEY,
                                                       request.user)
        authorize_url = DRIVE_FLOW.step1_get_authorize_url()
        return redirect(authorize_url)
    else:
        http = httplib2.Http()
        http = credential.authorize(http)

        drive_service = build('drive', 'v3', http=http)
        drive_request = drive_service.files().list(
            pageSize = 10,
            fields = 'nextPageToken, files(id, name)'
        )
        results = drive_request.execute()
        drive_request = drive_service.files().list_next(drive_request, results)
        results = drive_request.execute()
        items = results.get('files', [])
        context['items'] = items
        return render(request, 'drive.html', context)

def drive_auth_return(request):
    if not xsrfutil.validate_token(
            settings.SECRET_KEY,
            bytes(request.GET['state'], 'utf-8'),
            request.user):
        return  HttpResponseBadRequest()
    credential = DRIVE_FLOW.step2_exchange(request.GET)
    storage = DjangoORMStorage(DriveCredentialsModel, 'user', request.user, 'credential')
    storage.put(credential)
    return redirect('calendar')

def shortener(request):
    context = {}

    form = UrlForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            short_url = form.cleaned_data['url']

            url_service = build(
                'urlshortener',
                'v1',
                developerKey=settings.GOOGLE_API_KEY,
            )
            resp = url_service.url().get(shortUrl=short_url).execute()
            context['long_url'] = resp['longUrl']

    context['form'] = form
    return render(request, 'shortener.html', context)

def maps(request):
    return render(request, 'gmaps.html')

def translate(request):
    context = {}

    form = TransForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            trans = form.cleaned_data['text']

            url_service = build(
                'translate', 'v2',
                developerKey=settings.GOOGLE_API_KEY,
            )
            resp = url_service.translations().list(
                source='en',
                target='es',
                q=trans).execute()
            context['translated'] = resp['translations'][0]['translatedText']

    context['form'] = form
    return render(request, 'translate.html', context)

presentacion/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html class="no-js" lang="en">

<head>
<meta charset="UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<!-- Metas Page details-->
<title>Google API's</title>
<meta name="description" content="UX designer and web developer">
<meta name="author" content="">
<!-- Mobile Specific Metas-->
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!--main style-->
<link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/main.css' %}">
<link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/skins/blue.css' %}" data-name="skins">

<!--Syntax highlighting-->
<link rel="stylesheet" href="{% static 'reveal.js/lib/css/zenburn.css' %}">

<!--google font style-->
<link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
<!--font-family: 'Metrophobic', sans-serif;-->
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300italic,300,400italic,600italic,600,700italic,700' rel='stylesheet' type='text/css'>
<!--font-family: 'Open Sans', sans-serif; -->
<link href='http://fonts.googleapis.com/css?family=Roboto:400,700,400italic,500,300italic,300,100,500italic' rel='stylesheet' type='text/css'>
<!--font-family: 'Roboto', sans-serif; -->

<!-- font icon css style-->
<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
</head>
<body>

<!--wrapper start-->
<div class="wrapper" id="wrapper">
  <!-- Preloader -->
  <div id="preloader">
    <div id="status"></div>
  </div>
  <!--Header start -->
  <header>
    <!--menu start-->
    <div class="menu">
      <div class="navbar-wrapper">
        <div class="container">
          <!-- Navbar start -->
          <div class="navwrapper">
            <div class="navbar navbar-inverse navbar-static-top">
              <div class="container">
                <div class="logo"><a href="#"><span class="img-circle">g</span>oogle</a> </div>
                <nav class="navArea">
                  <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
                  </div>
                  <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav" id="navigation">
                      <li class="menuItem" id="home"><a href="{% url 'index' %} ">Expo</a></li>
                      <li class="menuItem"><a href="{% url 'gmaps' %}">Maps</a></li>
                      <li class="menuItem"><a href="#pricing">Translate</a></li>
                      <li class="menuItem"><a href="{% url 'shortener' %}">URL Shortener</a></li>
                      <li class="menuItem"><a href="{% url 'calendar' %}">Calendar</a></li>
                      <li class="menuItem"><a href="{% url 'drive' %}">Drive</a></li>
                    </ul>
                  </div>
                </nav>
              </div>
            </div>
          </div>
          <!-- Navbar end -->
        </div>
      </div>
    </div>
    <!--menu end-->
    <!-- banner start v4-->
    <div class="header_v4">
      <div class="banner row" id="banner">
        <div class="col-xs-12 col-sm-6 col-md-12 col-lg-12 noPadd slides-container" style="height:100%">
          <!--background slide show start-->
          <div class="slide">
            <img src="{% static 'images/header-image/wat4.gif' %}" alt="image01"> </div>
          <!--background slide show end-->
        </div>
      </div>
    </div>
    <!--banner end v4 -->

  </header>
  <!--Header end -->

{% block content %}{% endblock %}

  <!--Footer start-->
  <footer class="footer">
    <div class="container">
      <div class="row">
        <div class="pull-left">
          <p>&copy; 2016  Grey Team</p>
        </div>
      </div>
    </div>
  </footer>
  <!--Footer end -->
</div>
<!--wrapper end-->

<!--modernizr js-->
<script type="text/javascript" src="{% static 'js/modernizr.custom.26633.js' %}"></script>
<!--jquary min js-->
<script type="text/javascript" src="{% static 'js/jquery-1.11.2.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

<!--for placeholder jquery-->
<script type="text/javascript" src="{% static 'js/jquery.placeholder.js' %}"></script>

<!--for header jquery-->
<script src="{% static 'js/jquery.superslides.js' %}" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript">
"use strict";
	$('.header_v4 #banner').superslides({
	  animation: 'fade',
	  play: false
	});
</script>

<!--for portfolio jquery-->
<script src="{% static 'js/jquery.isotope.js' %}" type="text/javascript"></script>
<link type="text/css" rel="stylesheet" property="stylesheet" id="theme" href="{% static 'css/jquery-ui-1.8.16.custom.css' %}">
<link type="text/css" rel="stylesheet" property="stylesheet" href="{% static 'css/lightbox.min.css' %}">
<script type="text/javascript" src="{% static 'js/jquery.ui.widget.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.ui.rlightbox.js' %}"></script>

<!--for video lightbox -->
<link rel="stylesheet" property="stylesheet" href="{% static 'css/prettyPhoto.css' %}" type="text/css" media="screen" title="prettyPhoto main stylesheet" charset="utf-8" />
<script src="{% static 'js/jquery.prettyPhoto.js' %}" type="text/javascript"></script>

<!--contact form js-->
<script type="text/javascript" src="{% static 'js/jquery.contact.js' %}"></script>
<!--Newsletter js-->
<script type="text/javascript" src="{% static 'js/jquery.subscribe.js' %}"></script>

<!--about jquery-->
<script defer src="{% static 'js/jquery.flexslider.js' %}"></script>
<script src="{% static 'js/jquery.easing.js' %}"></script>
<script src="{% static 'js/jquery.mousewheel.js' %}"></script>
<script defer src="{% static 'js/slideroption.js' %}"></script>

<!--Home Testimonial -->
<script>


</script>

<!--for coundown jquary-->
<script type="text/javascript" src="{% static 'js/jquery.countTo.js' %}"></script>
<script type="text/javascript">
jQuery(function($) {
$(document).ready( function() {
  //enabling stickUp on the '.navbar-wrapper' class
		// Video responsive
		if ($(window).width()<400){
			$('.lb_mixed').rlightbox({
				videoWidth:320,
				videoHeight:280
			});
		} if ($(window).width()<640){
			$('.lb_mixed').rlightbox({
				videoWidth:600,
				videoHeight:360
			});
		} else {
			$('.lb_mixed').rlightbox({
				videoWidth:640,
				videoHeight:360
			});
		}

		// run rlightbox
		$( ".lb" ).rlightbox();
		$( ".lb_title-overwritten" ).rlightbox({overwriteTitle: true});

		$('.flexslider').flexslider({
			animation: "fade",
			animationLoop: true,
			slideshow: true,
			pauseOnAction: false,
			slideshowSpeed: 7000,
			controlNav: true,
			start: function(slider){
			$('body').removeClass('loading');
			}
		});

	var activeImage;

	var getmaxHeight = 0;
	$(".testimonialText li").each(function(index, element) {
        if($(this).height()>getmaxHeight){
			getmaxHeight = $(this).height();
			$(".footerTopContent").height(getmaxHeight);
			}
    });

    $(".testimonialText li").fadeTo("fast",0);
	$(".testimonialText li:first").fadeTo("fast",1);
	$(".imageSlide .imageBox").removeClass("activeImage");
	$(".imageSlide .imageBox:first").addClass("activeImage");
	$(".imageSlide .imageBox").mouseenter(function(){
		if(!$(this).hasClass("activeImage")){
			var gi = $(this).index();
			//console.log(gi);
			$(".imageSlide .imageBox").removeClass("activeImage");
			$(this).addClass("activeImage");
			$(".testimonialText li").fadeTo("fast",0);
			$(".testimonialText li:eq("+gi+")").fadeTo("fast",1);
			}
	})



function count(options) {
	var $this = $(this);
	options = $.extend({}, options || {}, $this.data('countToOptions') || {});
	$this.countTo(options);
}


	});

});
</script>

<!--for theme custom jquery-->
<script src="{% static 'js/custom.js' %}"></script>

<!--Syntax highlighting-->
<script src="{% static 'reveal.js/plugin/highlight/highlight.js' %}"></script>
<script>hljs.initHighlightingOnLoad();</script>
</body>
</html>

presentacion/templates/calendar.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
  <!--Membership features start -->
  <section class="white_section section_gap" id="features">
    <div class="container">
      <div class="heading">
        <h1><span>Google</span>Calendar</h1>
        <p>The Calendar API allows us to manipulate events and other calendar data. We can create and delete calendars and events.</p>
        <p>It provides the collection <code>events()</code> that includes the method <code>insert</code>, for adding events to the calendar of an user authenticated by OAuth. This method needs a the calendar ID and the body of the request as a dictionary.</p>
        <pre><code class="hljs">calendar_service = build('calendar', 'v3', ...)
body = {
    'start': { "date": '2016-11-09' },
    'end': { "date": '2016-11-10' },
    'summary': 'Event name'
}
calendar_request = calendar_service.events().insert(calendarId='primary', body=body)</code></pre>
        <p>For a detailed description of what keys the body dictionary accepts we have to look at the <a href="https://developers.google.com/resources/api-libraries/documentation/calendar/v3/python/latest/calendar_v3.events.html#insert">documentation</a></p>
      </div>
      
      <div class="row">
        {% if event_added %}
        <div class="alert alert-success" role="alert">The event has been added to your calendar.</div>
        {% endif %}
        <h2>Events</h2>
        {% if have_cred == False %}
          <p><a href="{% url 'add_event' 1 %}">Authorize access to your Google Calendar</a></p>
        {% endif %}
        {% for event in events %}
        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
          <div class="membership_listing"> <span><i class="fa fa-trophy"></i></span>
            <h3>{{ event.summary }}</h3>
            <p>{{ event.date }}</p>
          {% if have_cred == True %}
            <p><a href="{% url 'add_event' event.pk %}">Add event</a></p>
          {% endif %}
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </section>
  <!--/Membership features end -->
{% endblock %}

presentacion/templates/drive.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
  <!--Membership features start -->
  <section class="white_section section_gap" id="features">
    <div class="container">
      <div class="heading">
        <h1><span>Google</span>Drive</h1>
        <p>The Google Drive API is used to manage files in Drive. With this API we can upload, download and search files. We can also Detect changes and update sharing permissions. It required OAuth authentication from the user.</p>
        <pre><code class="hljs">
drive_service = build('drive', 'v3', http=http)
drive_request = drive_service.files().list(
    pageSize = 10,
    fields = 'nextPageToken, files(id, name)'
)
results = drive_request.execute()
drive_request = drive_service.files().list_next(drive_request, results)
results = drive_request.execute()
items = results.get('files', [])
context['items'] = items
return render(request, 'drive.html', context)
        </code></pre>
        <p></p>
      </div>
      
      <div class="row">
        <h2>Files</h2>
        {% if not items %}
        <p>No items found.</p>
        {% endif %}
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <ul>
        {% for item in items %}
            <li>{{ item.id }} - {{ item.name }}</li>
        {% endfor %}
          </ul>
        </div>
      </div>
    </div>
  </section>
  <!--/Membership features end -->
{% endblock %}

presentacion/templates/expo.html
{% load static %}
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

    <title>Google APIs</title>

    <link rel="stylesheet" href="{% static 'reveal.js/css/reveal.css' %}">
    <link rel="stylesheet" href="{% static 'reveal.js/css/theme/sky.css' %}">

    <!-- Theme used for syntax highlighting of code -->
    <link rel="stylesheet" href="{% static 'reveal.js/lib/css/zenburn.css' %}">
  </head>
  <body>
    <div class="reveal">
      <div class="slides">
        <!-- cambio de seccion-->
        <section>
          <h1 style="text-transform: none"> Google APIs</h1>
          <h2> Grey Team</h2>
          <ul>
            <li>Web Programming</li>
            <li>Wednesday November 9, 2016</li>
          </ul>
        </section>
        <!-- cambio de seccion-->
        <section data-background="{% static 'images/header-image/wat2.gif' %}"></section>
        <!-- cambio de seccion-->
        <section data-background-transition="concave">
          <section style="text-align: left;">
            <h2>APIs</h2>
            <h4>Application Programming Interfaces</h4>
            <p>Google provided APIs, which allow communication with Google Services and their integration to other services</p>
            <ul>
              <li>Search</li>
              <li>Gmail</li>
              <li>Translate</li>
              <li>Maps</li>
            </ul>
          </section>
          <section style="text-align: left;">
            <h2>Common Uses</h2>
            <ul>
              <li>User Registration</li>
              <li>Drive Apps</li>
              <li>Custom Search</li>
              <li>App Engine apps</li>
              <li>Gadgets</li>
            </ul>
          </section>
          <section style="text-align: left;">
            <h2>Client Libraries</h2>
            <p>Provided by Google to make it easier to access the APIs from different languages.</p>
            <ul>
              <li><strong>Python</strong></li>
              <li>Java</li>
              <li>JavaScript</li>
              <li>.NET</li>
              <li>Objective-C</li>
              <li>PHP</li>
            </ul>
          </section>
        </section>
        <!-- cambio de seccion-->
        <section>
          <section>
            <h2>Authentication and Autorization</h2>
            <p style="text-align: left;">All API calls must use either simple or authorized access. Many API methods required authorized access, but some can use either.</p>
          </section>
          <section style="text-align: left;">
            <h2>Simple access</h2>
            <ul>
              <li>Doesn't access any private user data.</li>
              <li>Needs an API key.</li>
            </ul>
          </section>
          <section style="text-align: left;">
            <h2>Authorized access</h2>
            <ul>
              <li>Accesses private user data.</li>
              <li>Before calling them, user must grant your app access to their data.</li>
              <li>Needs client ID and client secret.</li>
            </ul>
          </section>
          <section style="text-align: left;">
            <p>Using some of this APIs require authorization.</p>
            <p><strong>Requirements</strong></p>
              <ul>
                <li><strong>Credentials</strong></li>
                <li>Access Token</li>
                <li>Use the Token for Authorization</li>
              </ul>
          </section>
        </section>

        <section>
          <section>
            <h2>Client Library for Python</h2>
          </section>
          <section>
            <h3>Installation</h3>
            <pre><code class="hljs">$ pip install --upgrade google-api-python-client</code></pre>
          </section>
          <section>
            <h3>Service object</h3>
            <pre><code class="hljs">from apiclient.discovery import build
service = build('api_name', 'api_version', ...)</code></pre>
          </section>
          <section>
            <h3>Collection</h3>
            <p>Represents a resource.</p>
            <pre><code class="hljs">collection = service.url()</code></pre>
          </section>
          <section>
            <h3>Collection method</h3>
            <p>Returns a HttpRequest but doesn't send it.</p>
            <pre><code class="hljs">request = collection.get(shortUrl='url')</code></pre>
          </section>
          <section>
            <h3>Execution</h3>
            <p>To execute the request and get a response we call the execute() method.</p>
            <pre><code class="hljs">response = request.execute()</code></pre>
            <p>or</p>
            <pre><code class="hljs">response = service.url().get(shortUrl='url').execute()</code></pre>
          </section>
          <section>
            <h3>Response</h3>
            <p>The response is a dictionary.</p>
            <pre><code class="hljs">{
  "kind": "urlshortener#url",
  "id": "https://goo.gl/yBCFkX",
  "longUrl": "https://developers.google.com/resources/api-libraries/documentation/urlshortener/v1/python/latest/urlshortener_v1.url.html"
}</code></pre>
          </section>
        </section>

        <section>
          <section>
            <h2>Examples</h2>
            <ul style="text-align: left;">
                <li><a href="{% url 'gmaps' %}">Google Maps</a></li>
              <li><a href="{% url 'calendar' %}">Calendar</a></li>
            </ul>
          </section>
        </section>
      </div>
    </div>

    <script src="{% static 'reveal.js/lib/js/head.min.js' %}"></script>
    <script src="{% static 'reveal.js/js/reveal.js' %}"></script>

    <script>
      // More info https://github.com/hakimel/reveal.js#configuration
      Reveal.initialize({
        history: true,

        // More info https://github.com/hakimel/reveal.js#dependencies
        dependencies: [
          { src: '{% static 'reveal.js/plugin/markdown/marked.js' %}' },
          { src: '{% static 'reveal.js/plugin/markdown/markdown.js' %}' },
          { src: '{% static 'reveal.js/plugin/notes/notes.js' %}', async: true },
          { src: '{% static 'reveal.js/plugin/highlight/highlight.js' %}', async: true, callback: function() { hljs.initHighlightingOnLoad(); } }
        ]
      });
    </script>
  </body>
</html>

presentacion/templates/shortener.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
  <!--Membership features start -->
  <section class="white_section section_gap" id="features">
    <div class="container">
      <div class="heading">
        <h1><span>Google</span>URL Shortener</h1>
        <p>The URL Shortener API lets us create, inspect, and manage goo.gl short URLs.</p>
        <p>It provides the collection <code>url()</code> that includes the methods:</p>
        <ul>
          <li><strong>get()</strong>: Expands a short URL or gets analytics.</li>
          <li><strong>insert()</strong>: Creates a new short URL.</li>
          <li><strong>list()</strong>: Gets a list of URLs shortened by a user.</li>
        </ul>
        <pre><code class="hljs">short_url = form.cleaned_data['url']

url_service = build(
    'urlshortener',
    'v1',
    developerKey=settings.GOOGLE_API_KEY,
)
resp = url_service.url().get(shortUrl=short_url).execute()
context['long_url'] = resp['longUrl']</code></pre>
      </div>

      <div class="row">
        <h2>Expand a goo.gl URL</h2>
        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
          <form method="POST">
          {% csrf_token %}
          <p><label for="id_url">Url:</label> <input id="id_url" maxlength="200" name="url" type="text" value="http://goo.gl/l6MS" required style="width: 90%"/></p>
          <input class="btn" type="submit" value="Expand">
          </form>
        </div>
        <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8">
           {{ long_url }}
        </div>
      </div>
    </div>
  </section>
  <!--/Membership features end -->
{% endblock %}

presentacion/templates/translate.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
  <!--Membership features start -->
  <section class="white_section section_gap" id="features">
    <div class="container">
      <div class="heading">
        <h1><span>Google</span>Translator</h1>
        <p>With Google Translate API, you can dynamically translate text between thousands of language pairs.</p>
        <p>The Google Translate API lets websites and programs integrate with Google Translate API programmatically.</p>
        <p>It provides the collection <code>language()</code> that includes the methods:</p>

        <ul>
          <li><strong>detections()</strong>: Detect the language of text.</li>
          <li><strong>language()</strong>: List the source/target languages supported by the API.</li>
          <li><strong>translation()</strong>: Returns text translations from one language to another.</li>
        </ul>
        <pre><code class="hljs">short_url = form.cleaned_data['url']

            url_service = build(
                'urlshortener',
                'v1',
                developerKey=settings.GOOGLE_API_KEY,
            )
            resp = url_service.url().get(shortUrl=short_url).execute()
            context['long_url'] = resp['longUrl']</code></pre>
      </div>

      <div class="row">
        <h2>Translate to Spanish</h2>
        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
          <form method="POST">
          {% csrf_token %}
          <p><label for="id_url">Text:</label> <input id="id_url" maxlength="200" name="text" type="text" value="" required style="width: 90%"/></p>
          <input class="btn" type="submit" value="Expand">
          </form>
        </div>
        <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8">
           {{ translated }}
        </div>
      </div>
    </div>
  </section>
  <!--/Membership features end -->
{% endblock %}